# Generated by Django 2.2.3 on 2019-07-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_ideia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(default='', max_length=255, verbose_name='Senha'),
            preserve_default=False,
        ),
    ]
