# Generated by Django 2.2.3 on 2019-07-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_pessoa_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='E-mail'),
        ),
    ]
